config/routes.rb
Rails.application.routes.draw do
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash

    end
  end
  resources :carts do
    collection do
      delete :clean
      get :checkout
    end
  end
  namespace :account do
    resources :orders
  end
  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end
  resources :cart_items do
    member do
      post :add_quantity
      post :remove_quantity
    end
  end
  resources :users, only: [:index]
  resources :messages, only: [:new, :create]
  resources :categories
  resources :products do
    put :favorite, on: :member
    resources :favorite do
      end
    member do
      post :add_to_cart
      post :upvote
      post :add_buying_quantity
      post :remove_buying_quantity
    end
    collection do
      get :search
    end
    resources :posts
  end
   devise_for :user, controllers: {
     passwords: 'users/passwords',
     registrations: 'users/registrations',
     sessions: 'users/sessions'
   }
  root 'welcome#index'

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def clean!
    cart_items.destroy_all
  end

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = product.buying_quantity
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/graphic.rb
class Graphic < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :post
end

app/models/order.rb
class Order < ApplicationRecord
  include Tokenable
  
  belongs_to :user
  has_many :product_lists
  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  def set_payment_with!(method)
    self.update_columns(payment_method: method)
  end

  def pay!
    self.update_columns(is_paid: true )
  end

include AASM
  aasm do
  state :order_placed, initial: true
  state :paid
  state :shipping
  state :shipped
  state :order_cancelled
  state :good_returned


  event :make_payment, after_commit: :pay! do
    transitions from: :order_placed, to: :paid
  end

  event :ship do
    transitions from: :paid,         to: :shipping
  end

  event :deliver do
    transitions from: :shipping,     to: :shipped
  end

  event :return_good do
    transitions from: :shipped,      to: :good_returned
  end

  event :cancell_order do
    transitions from: [:order_placed, :paid], to: :order_cancelled
  end
end
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
belongs_to :product
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_many :graphics
  accepts_nested_attributes_for :graphics
  validates :content, presence: true 
end

app/models/print.rb
class Print < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :photos
  accepts_nested_attributes_for :photos
  belongs_to :category
  validates :category_id, presence: true
  belongs_to :user
  has_many :favorites
  has_many :fans, through: :favorites, source: :user
  has_many :votes, dependent: :destroy
  has_many :posts
  has_many :prints
  accepts_nested_attributes_for :prints
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
           acts_as_messageable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :orders

         def admin?
           is_admin
         end
         def mailboxer_email(object)
           email
         end
         has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "25x25#" }, :default_url => "/images/:style/missing.png"
         validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

         has_many :products
         has_many :favorites
         has_many :favorite_products, :through => :favorites, :source => :product
         def is_favorite_of?(product)
           favorite_products.include?(product)
         end
         has_many :posts
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :product
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def clean
    if current_cart.cart_items.present?
    current_cart.clean!
    flash[:warning] = "已清空购物车"
  else
    flash[:alert] = "购物车内没有物品,请先加入物品"
    end
    redirect_to :back
  end
  def checkout
    @order = Order.new 
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def emojify(content, **options)
    Twemoji.parse(h(content), options).html_safe if content.present?
  end
end

app/helpers/favorite_helper.rb
module FavoriteHelper
	def last_item(index)
		if index > 0 && (index + 1) % 5 == 0
		  "productList-lastItem"
		end
	end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end 

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options(chosen_recipient = nil)
    options_for_select(User.all.map { |user| [user.email, user.id] }, chosen_recipient.nil? ? nil : chosen_recipient.id)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
   def render_order_paid_state(order)
     if order.is_paid?
       "已付款"
     else
       "未付款"
     end
   end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_product_list.erb
<div class="cartProducts-list">
    <% current_cart.cart_items.includes(:product).each do |cart_item| %>
      <div class="cartProducts-listItem clearfix pt20 pb20 mb10 border">
        <div class="item-pic fl border ml30">
          <%= link_to product_path(cart_item.product) do %>
            <% if cart_item.product.photos[0].present? %>
               <%= image_tag(cart_item.product.photos[0].avatar.thumb.url) %>
            <% else %>
              <%= image_tag("http://placehold.it/200x200&text=No Pic") %>
            <% end %>
          <% end %>
        </div>
        <div class="item-msg fl">
          <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
        </div>
        <div class="item-price fl tc"><%= cart_item.product.price %></div>
        <div class="item-quantity fl tc">
          <div class="countNumber">
            <%= link_to("-", remove_quantity_cart_item_path(cart_item.product_id), class: "countNumber-btn countNumber-btn-sub", method: :post, remote: true) %>
            <input class="countNumber-input" type="text" value="<%= cart_item.quantity %>">
            <%= link_to("+", add_quantity_cart_item_path(cart_item.product_id), class: "countNumber-btn countNumber-btn-plus", method: :post, remote: true) %>
          </div>
        </div>
        <div class="item-total fl tc"><%= cart_item.product.price * cart_item.quantity  %></div>
        <div class="item-operation fl tc"><%= link_to("删除", cart_item_path(cart_item.product_id), method: :delete, class: "delete-btn", remote: true)%></div>
      </div>
    <% end %>
  </div>

  <div class="account border clearfix mt30 p20 mb20">
    <%= link_to("确认结账", checkout_carts_path, class: "intro-text-btn add-cart pl15 pr15 ml20 tc col-red f20 bg-red fr") %>
    <p class="fr mt10 mr20">合计: <strong class="col-red f18">￥<%= render_cart_total_price(current_cart) %></strong></p>
  </div>

app/views/carts/checkout.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h2> 购物明细 </h2>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th width-"80%">商品明细</th>
            <th>单价</th>
            <th>数量</th>
          </tr>
        </thead>
      <tbody>

        <% current_cart.cart_items.includes(:product).each do |cart_item| %>
        <tr>
          <td>
            <%= link_to(cart_item.product.title, product_path(cart_item.product)) %>
          </td>
          <td>
            <%= cart_item.product.price %>
          </td>
          <td>
            <%= cart_item.quantity %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="total clearfix">
      <span class="pull-right">
        总计<%= render_cart_total_price(current_cart) %> CNY
      </span>
    </div>

    <hr>

    <h2> 订单资讯 </h2>

    <div class="order-form">

      <%= simple_form_for @order do |f| %>


      <legend>订购人</legend>
      <div class="gorm-group col-lg-6">
        <%= f.input :billing_name, :label => '姓名' %>
      </div>
      <div class="form-group col-lg-6">
        <%= f.input :billing_address, :label => '地址' %>
      </div>

      <legend>收货人</legend>
      <div class="form-group col-lg-6">
        <%= f.input :shipping_name, :label => '姓名' %>
      </div>
      <div class="form-group col-lg-6">
        <%= f.input :shipping_address, :label => '地址' %>
      </div>

      <div class="checkout">
        <%= f.submit "生成订单", class: "btn btn-lg btn-danger pull-right",
                      data: { disable_with: "Submitting..."} %>
      </div>
      <% end %>
    </div>
    </div>
  </div>

</div>

app/views/carts/index.html.erb
<div class="w1200 clearfix bc mt30 pb20">
  <div class="logo fl"><%=link_to("小小食杂铺", products_path, class: "col-red")%></div>
</div>

<div class="w1200 clearfix bc mt20">
  <ul class="cartProducts-title clearfix bg-gray border">
    <li class="tc fl cartProducts-title-msg">商品信息</li>
    <li class="tc fl cartProducts-title-price">单价</li>
    <li class="tc fl cartProducts-title-quantity">数量</li>
    <li class="tc fl cartProducts-title-total">小计（元）</li>
    <li class="tc fl cartProducts-title-operation">操作</li>
  </ul>

  <div class="cartPage-productList">
    <%= render :partial => "product_list" %>
  </div>
</div>