config/routes.rb
Rails.application.routes.draw do
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash

    end
  end
  resources :carts do
    collection do
      delete :clean
      get :checkout
    end
  end
  namespace :account do
    resources :orders
  end
  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end
  resources :cart_items do
    member do
      post :add_quantity
      post :remove_quantity
    end
  end
  resources :users, only: [:index]
  resources :messages, only: [:new, :create]
  resources :categories
  resources :products do
    put :favorite, on: :member
    resources :favorite do
      end
    member do
      post :add_to_cart
      post :upvote
      post :add_buying_quantity
      post :remove_buying_quantity
    end
    collection do
      get :search
    end
    resources :posts
  end
   devise_for :user, controllers: {
     passwords: 'users/passwords',
     registrations: 'users/registrations',
     sessions: 'users/sessions'
   }
  root 'welcome#index'

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :photos
  accepts_nested_attributes_for :photos
  belongs_to :category
  validates :category_id, presence: true
  belongs_to :user
  has_many :favorites
  has_many :fans, through: :favorites, source: :user
  has_many :votes, dependent: :destroy
  has_many :posts
  has_many :prints
  accepts_nested_attributes_for :prints
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  def index
    @products = Product.includes(:photos).includes(:category).all
  end
  def new
    @product = Product.new
    @categories = Category.all.map { |c| [c.name, c.id] } #这一行为加入的代码
    @photo = @product.photos.build #for multi-pics
    @print = @product.prints.build #for multi-pics

  end
  def show
  end
  def edit
    @categories = Category.all.map { |c| [c.name, c.id] } #这一行为加入的代码
  end

    def create
      @product = Product.new(product_params)
      @product.category_id = params[:category_id]
      if @product.save
        if params[:photos] != nil
            params[:photos]['avatar'].each do |a|
            @photo = @product.photos.create(:avatar => a)
        end
        if params[:prints] != nil
             params[:prints]['avatar'].each do |a|
             @print = @product.prints.create(:avatar => a)
         end
     end
        end

        redirect_to admin_products_path
      else
        render :new
      end
    end
    def update
       @product.category_id = params[:category_id]
       if params[:photos] != nil
           @product.photos.destroy_all #need to destroy old pics first
           params[:photos]['avatar'].each do |a|
            @picture = @product.photos.create(:avatar => a)
         end
       end
        if params[:prints] != nil
            @product.prints.destroy_all #need to destroy old pics first

            params[:prints]['avatar'].each do |a|
            @picnip = @product.prints.create(:avatar => a)
          end
        end
         @product.update(product_params)
         redirect_to admin_products_path
     end
  def destroy
    @product.destroy
    redirect_to admin_products_path
  end
  private
  def find_product
     @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image, :category_id, :detail)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]
  before_action :authenticate_user!, only: [:favorite]
  before_action :find_product, only: [:show, :add_to_cart, :favorite, :upvote, :add_buying_quantity, :remove_buying_quantity]
  before_action :get_products, only: [:index, :add_to_cart, :favorite]
  respond_to :js

  def index
  end
  def show
    @photos = @product.photos.all
    @posts = @product.posts.includes(:graphics).includes(:user)
    @prints = @product.prints.all
    if @posts.blank?
      @avg_post = 0
      @avg_look = 0
      @avg_price = 0
    else
      @avg_post = @posts.average(:rating).round(2)
      @avg_look = @posts.average(:look).round(2)
      @avg_price = @posts.average(:price).round(2)
    end
  end
  def search
		@products = Product.ransack({:title_cont => @q}).result(:distinct => true)
	end
  def add_to_cart

    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
      @product.quantity -= @product.buying_quantity
      @product.buying_quantity = 1
      @product.save
    else
      # flash[:warning] = "不能重复加入商品"
      # redirect_to :back
    end
    respond_to do |format|
      format.js   { render :layout => false }
    end
  end

  def add_buying_quantity
    if @product.buying_quantity <= @product.quantity
      @product.buying_quantity +=1
      @product.save
      # redirect_to :back
      respond_to do |format|
        format.js   { render :layout => false }
      end
    end
  end

  def remove_buying_quantity
    if @product.buying_quantity > 1
      @product.buying_quantity -= 1
      @product.save
      # redirect_to :back
      respond_to do |format|
        format.js   { render :layout => false }
      end
    end
  end
  def favorite

    type = params[:type]
    if type == "favorite"
    current_user.favorite_products << @product
    redirect_to :back
    elsif type == "unfavorite"
    current_user.favorite_products.delete(@product)
    redirect_to :back

    else
    redirect_to :back
    end
  end

  def upvote
    @product.votes.create
    @product.like = @product.votes.count
    @product.save
    redirect_to :back
  end
  protected

  def find_product
    @product = Product.find(params[:id])
  end
  def validate_search_key
    @q = params[:query_string].gsub(/\|\'|\/|\?/, "") if params[:query_string].present?
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def trancate(string, length = 20)
	  string.size > length+5 ? [string[0,length],string[-5,5]].join("...") : string
	end

	def last_item(index)
		if index > 0 && (index + 1) % 5 == 0
		  "productList-lastItem"
		end
	end
end

app/views/admin/products/edit.html.erb
<h2> Edit Product </h2>

<%= simple_form_for [:admin, @product ] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

  <% if @product.photos.present? %>
    <span>小图</span> <br>
    <% @product.photos.each do |p| %>
      <%= image_tag p.avatar.thumb.url %><br>
    <% end %>
  <% end %>

  <div class="group">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar, :multiple => true, name: "photos[avatar][]" %>
  </div>

  <% if @product.prints.present? %>
      <span>详情图</span> <br>
      <% @product.prints.each do |p| %>
        <%= image_tag p.avatar.thumb.url %><br>
      <% end %>
  <% end %>

    <div class="group">
      <%= f.label :avatar %><br>
      <%= f.file_field :avatar, :multiple => true, name: "prints[avatar][]" %>
    </div>

 <div class="group">
   <%= f.input :detail %>
 </div>
  <%= f.select :category_id, @categories %>
  <%= f.submit "Sbumit", data: { disable_with: "Submitting..."} %>

  <% end %>

app/views/admin/products/index.html.erb
<h2> Product List </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增商品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
  <%= link_to("新增类别", categories_path, class: "btn btn-primary btn-sm") %>
  <%= link_to("订单页面", admin_orders_path, class: "btn btn-primary btn-sm") %>
</div>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width="220">Product Pic</th>
      <th>Name</th>
      <th>Price</th>
      <th>category</th>
      <th width="100px"> Options </th>
      <th>timestamp</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do|product| %>
    <tr>
      <td>
        <%= product.id %>
      </td>
      <td>
        <%= link_to product_path(product) do %>
          <% if product.photos.present? %>
            <%#= image_tag(product.image.thumb.url, class: "thumbnail") %>
            <%= image_tag(product.photos[0].avatar.thumb.url, class: "thumbnail") %>
          <% else %>
            <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
          <% end %>
        <% end %>
      </td>
      <td>
        <%= product.title%>
      </td>
      <td>
        <%= product.price%>
      </td>
      <td>
        <%= product.category.name %>
      </td>
      <td>
        <%= link_to("Edit", edit_admin_product_path(product )) %> |<br>
        <%= link_to("Destroy", admin_product_path(product), :method => :delete, :data => { :confirm => "Are you sure?" }) %>
      </td>
      <td> <%= local_time(product.created_at)%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<div id="task-form" style="display:none;"></div>

app/views/admin/products/new.html.erb
<h2> New Product </h2>

<%= simple_form_for [:admin, @product] do |f| %>

  <div class="group">
    <%= f.input :title %>
  </div>

  <div class="group">
    <%= f.input :description %>
  </div>

  <div class="group">
    <%= f.input :quantity %>
  </div>

  <div class="group">
    <%= f.input :price %>
  </div>

  <div class="group">
    <%#= f.input :image, as: :file%>
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar, :multiple => true, name: "photos[avatar][]" %>
  </div>
  <div class="group">
    <%= f.input :detail %>
  </div>

  <div class="group">
    <%#= f.input :image, as: :file %>
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar, :multiple => true, name: "prints[avatar][]" %>
  </div>
  <%= select_tag(:category_id, options_for_select(@categories)) %>
  <%= f.submit "Submit", data: { disable_with: "Submitting..."} %>

<% end %>