config/routes.rb
Rails.application.routes.draw do
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash

    end
  end
  resources :carts do
    collection do
      delete :clean
      get :checkout
    end
  end
  namespace :account do
    resources :orders
  end
  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end
  resources :cart_items do
    member do
      post :add_quantity
      post :remove_quantity
    end
  end
  resources :users, only: [:index]
  resources :messages, only: [:new, :create]
  resources :categories
  resources :products do
    put :favorite, on: :member
    resources :favorite do
      end
    member do
      post :add_to_cart
      post :upvote
      post :add_buying_quantity
      post :remove_buying_quantity
    end
    collection do
      get :search
    end
    resources :posts
  end
   devise_for :user, controllers: {
     passwords: 'users/passwords',
     registrations: 'users/registrations',
     sessions: 'users/sessions'
   }
  root 'welcome#index'

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :photos
  accepts_nested_attributes_for :photos
  belongs_to :category
  validates :category_id, presence: true
  belongs_to :user
  has_many :favorites
  has_many :fans, through: :favorites, source: :user
  has_many :votes, dependent: :destroy
  has_many :posts
  has_many :prints
  accepts_nested_attributes_for :prints
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  def index
    @products = Product.includes(:photos).includes(:category).all
  end
  def new
    @product = Product.new
    @categories = Category.all.map { |c| [c.name, c.id] } #这一行为加入的代码
    @photo = @product.photos.build #for multi-pics
    @print = @product.prints.build #for multi-pics

  end
  def show
  end
  def edit
    @categories = Category.all.map { |c| [c.name, c.id] } #这一行为加入的代码
  end

    def create
      @product = Product.new(product_params)
      @product.category_id = params[:category_id]
      if @product.save
        if params[:photos] != nil
            params[:photos]['avatar'].each do |a|
            @photo = @product.photos.create(:avatar => a)
        end
        if params[:prints] != nil
             params[:prints]['avatar'].each do |a|
             @print = @product.prints.create(:avatar => a)
         end
     end
        end

        redirect_to admin_products_path
      else
        render :new
      end
    end
    def update
       @product.category_id = params[:category_id]
       if params[:photos] != nil
           @product.photos.destroy_all #need to destroy old pics first
           params[:photos]['avatar'].each do |a|
            @picture = @product.photos.create(:avatar => a)
         end
       end
        if params[:prints] != nil
            @product.prints.destroy_all #need to destroy old pics first

            params[:prints]['avatar'].each do |a|
            @picnip = @product.prints.create(:avatar => a)
          end
        end
         @product.update(product_params)
         redirect_to admin_products_path
     end
  def destroy
    @product.destroy
    redirect_to admin_products_path
  end
  private
  def find_product
     @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image, :category_id, :detail)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :validate_search_key, only: [:search]
  before_action :authenticate_user!, only: [:favorite]
  before_action :find_product, only: [:show, :add_to_cart, :favorite, :upvote, :add_buying_quantity, :remove_buying_quantity]
  before_action :get_products, only: [:index, :add_to_cart, :favorite]
  respond_to :js

  def index
  end
  def show
    @photos = @product.photos.all
    @posts = @product.posts.includes(:graphics).includes(:user)
    @prints = @product.prints.all
    if @posts.blank?
      @avg_post = 0
      @avg_look = 0
      @avg_price = 0
    else
      @avg_post = @posts.average(:rating).round(2)
      @avg_look = @posts.average(:look).round(2)
      @avg_price = @posts.average(:price).round(2)
    end
  end
  def search
		@products = Product.ransack({:title_cont => @q}).result(:distinct => true)
	end
  def add_to_cart

    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
      @product.quantity -= @product.buying_quantity
      @product.buying_quantity = 1
      @product.save
    else
      # flash[:warning] = "不能重复加入商品"
      # redirect_to :back
    end
    respond_to do |format|
      format.js   { render :layout => false }
    end
  end

  def add_buying_quantity
    if @product.buying_quantity <= @product.quantity
      @product.buying_quantity +=1
      @product.save
      # redirect_to :back
      respond_to do |format|
        format.js   { render :layout => false }
      end
    end
  end

  def remove_buying_quantity
    if @product.buying_quantity > 1
      @product.buying_quantity -= 1
      @product.save
      # redirect_to :back
      respond_to do |format|
        format.js   { render :layout => false }
      end
    end
  end
  def favorite

    type = params[:type]
    if type == "favorite"
    current_user.favorite_products << @product
    redirect_to :back
    elsif type == "unfavorite"
    current_user.favorite_products.delete(@product)
    redirect_to :back

    else
    redirect_to :back
    end
  end

  def upvote
    @product.votes.create
    @product.like = @product.votes.count
    @product.save
    redirect_to :back
  end
  protected

  def find_product
    @product = Product.find(params[:id])
  end
  def validate_search_key
    @q = params[:query_string].gsub(/\|\'|\/|\?/, "") if params[:query_string].present?
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def trancate(string, length = 20)
	  string.size > length+5 ? [string[0,length],string[-5,5]].join("...") : string
	end

	def last_item(index)
		if index > 0 && (index + 1) % 5 == 0
		  "productList-lastItem"
		end
	end
end

app/views/products/_cart.html.erb
<div class="cart bg-gray f12 pl20 pr20 pr pa">
	<%= link_to carts_path do %>
    <i class="fa fa-shopping-cart cart-icon col-red f16 mr10 tc"></i>我的购物车
    <span class="products_count"><%= current_cart.products.count %></span>
  <% end %>
</div>

<div class="previewProductsList pa bg-gray border">
	<% if current_cart.cart_items.includes(:product).present? %>
		<% current_cart.cart_items.each do |cart_item| %>
			<div class="previewProductsList-item clearfix pt10 pb10">
				<%= link_to product_path(cart_item.product), class: "previewProductsList-item-image fl mr20 ml10 border" do %>
					<% if cart_item.product.photos[0].present? %>
						 <%= image_tag(cart_item.product.photos[0].avatar.thumb.url) %>
					<% else %>
						<%= image_tag("http://placehold.it/200x200&text=No Pic") %>
					<% end %>
				<% end %>
				<%= link_to(cart_item.product.title, product_path(cart_item.product), class: "previewProductsList-item-title fl f12") %>
				<div class="previewProductsList-item-info fr f12 pr10">
					<p class="tr"><span class="fb">￥<%= cart_item.product.price %></span> x <span class="fb"><%= cart_item.quantity %></span></p>
					 
					<%= link_to("删除", cart_item_path(cart_item.product_id), method: :delete, class: "delete-btn fr", remote: true)%>

				</div>
			</div>
		<% end %>
		<div class="bottom bg-gray p10 clearfix">
			<p class="info fl f12 tr">合计 ￥<%= render_cart_total_price(current_cart) %></p>
			<%= link_to("确认结账", checkout_carts_path, class: "s-btn add-cart pl15 pr15 ml20 tc col-red f12 bg-red fr") %>
		</div>
	<% else %>
		<p class="empty-message fs pt10 tc f12">购物车还没有商品，赶紧添加吧</p>
	<% end %>
</div>

app/views/products/_cart_btn.html.erb
<% if @product.quantity.present? && @product.quantity > 0 %>
    <%= link_to("加入购物车", add_to_cart_product_path(@product),
        :method => :post,
        :remote => true,
        :class => "intro-text-btn addCartBtn add-cart pl15 pr15 mt30 ml20 tc col-red f20 bg-red") %>
<% else %>
  <a href="javascript:;" class="intro-text-btn add-cart pl15 pr15 mt20 ml20 tc col-red f20 bg-red btn-disabled">已售完</a>
<% end %>

app/views/products/_menu.html.erb
<% if params[:controller] == ('products') && params[:action] == ('show') %>
  <div class="menu-wrap">
    <ul class="menuList clearfix w1200 f16 bc">
      <li class="menuList-item fl pl20 pr20">
        <%= link_to("首页", products_path)%>
      </li>
      <% Category.all.each do |category| %>
        <li class="menuList-item fl <%= 'menuList-activeItem' if @product.category.name == category.name %>">
          <%= link_to category.name, products_path(category: category.name), class: "link" %>
        </li>
      <% end %>
    </ul>
  </div>
<% else %>
  <div class="menu-wrap">
    <ul class="menuList clearfix w1200 f16 bc">
      <li class="menuList-item fl pl20 pr20 <%= 'menuList-activeItem' if !params[:category] %>">
        <%= link_to("首页", products_path)%>
      </li>
      <% Category.all.each do |category| %>
        <li class="menuList-item fl <%= 'menuList-activeItem' if params[:category] == category.name %>">
          <%= link_to category.name, products_path(category: category.name), class: "link" %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/products/_product_item.html.erb
<li class="fl productList-item p15 pr <%= last_item(index) %>">
  <p class="productList-item-pic w200 h200">
    <%= link_to product_path(product) do %>
      <% if product.photos.present? %>
        <%= image_tag(product.photos[0].avatar.thumb.url) %>
      <% else %>
        <%= image_tag("http://placehold.it/418x418&text=No Pic") %>
      <% end %>
    <% end %>
  </p>
  <p class="productList-item-price fb col-red f18 mt10">￥<%= product.price %></p>
  <p class="productList-item-name ell">
    <%= link_to product_path(product) do %>
       <%= product.title %>
    <% end %>
  </p>
  <p class="productList-item-desc mt5 f12"><%= product.description %></p>
  <% if product.quantity > 0 %>
    <%= link_to add_to_cart_product_path(product), :method => :post, class: "addCartBtn productList-item-cartBtn pa border f18", :remote => true do %>
      <i class="fa fa-shopping-cart col-red"></i>
    <% end %>
  <% end %>
  <% if product.quantity <= 0 %>
    <p class="productList-item-sellout f20 tc">已售完</p>
  <% end %>
</li>

app/views/products/_product_list.html.erb
<ul class="productList clearfix pb20">
  <% @products.each_with_index do |product, index| %>
    <%= render :partial => "product_item", locals: { product: product, index: index } %>
  <% end %>
</ul>

app/views/products/_product_search.html.erb
<p><%=  product.title %></p>
<%= link_to product_path(product) do %>
  <% if product.photos.present? %>
    <%= image_tag(product.photos[0].avatar.thumb.url) %>
  <% else %>
    <%= image_tag("http://placehold.it/418x418&text=No Pic") %>
  <% end %>
<% end %>
<p>价格: ￥<%= product.price %></p>
<p>描述: <%= product.description %></p>

app/views/products/_search_bar.html.erb
<div class="search clearfix pr">
  <%= form_tag search_products_path , :method => :get do %>
    <input class="search-input fl w400" type="text" class="form-control" name="query_string" value="<%= params[:q] %>" placeholder="输入你要搜索的商品">
    <button type="submit" class="search-button pa tc"><i class="fa fa-search col-red"></i></button>
  <% end %>
</div>

app/views/products/add_buying_quantity.js.erb
$('.countNumber-btn-plus').bind('ajax:success', function(e, data) {
	$('.countNumber-input').val('<%= @product.buying_quantity %>')
});

app/views/products/add_to_cart.js.erb
$('.addCartBtn').bind('ajax:success', function(e, data) {
   $('.cart-wrap').html('<%= escape_javascript render(:partial => "products/cart") %>')
   $('#quantity').html('<%= @product.quantity %>')
   $('.intro-text-btnWrap').html('<%= escape_javascript render(:partial => "products/cart_btn") %>')
   $('.countNumber-input').val('<%= @product.buying_quantity %>')
});

app/views/products/index.html.erb
<div class="header_placeholder h80"></div>    
<div class="header">
  <div class="w1200 clearfix bc mt30 pb20 header_content pr">
    <div class="logo fl"><%=link_to("小小食杂铺", products_path, class: "col-red")%></div>
    <div class="fl ml40 mt10">
      <%= render :partial => "products/search_bar" %>
    </div>
    <div class="pa mt10 cart-wrap">
      <%= render :partial => "products/cart" %>
    </div>
  </div>
</div>
<%= render :partial => "products/menu" %>
<div class="minHeight1000 bg-gray">
  <div class="banner tc pt30 w1200 bc">
    <div id="myCarousel" class="carousel slide">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
     </ol>
     <div class="carousel-inner">
        <div class="item active">
         <a href="javacript:;">
          <img src="https://ww2.sinaimg.cn/large/006tNc79ly1fcrl5afeqhj30xc0afgpx.jpg">
          <div class="carousel-caption"></div>
         </a>
        </div>
        <div class="item">
         <a href="javacript:;">
          <img src="https://vipweb.bs2cdn.yy.com/vipinter_de4f123bb220482e93649571a1491572.jpg">
          <div class="carousel-caption"></div>
         </a>
        </div>
        <div class="item">
         <a href="javacript:;">
          <img src="https://ww2.sinaimg.cn/large/006tNc79ly1fcrlcb0knhj30xc0afwib.jpg">
          <div class="carousel-caption"></div>
         </a>
        </div>
      </div>
    </div>
  </div>
  <div class="order clearfix mt30 w1200 bc">
    <p class="fl title pl20 pr20">商品排序：</p>
    <ul class="fl orderList">
      <li class="fl orderList-orderItem pl20 pr20 <%= 'orderList-activeItem' if !params[:order] %>"><%= link_to("新品", products_path) %></li>
      <li class="fl orderList-orderItem pl20 pr20 <%= 'orderList-activeItem' if params[:order] == 'by_product_quantity' %>"><%= link_to("销量", products_path(:order => "by_product_quantity")) %></li>
      <li class="fl orderList-orderItem pl20 pr20 <%= 'orderList-activeItem' if params[:order] == 'by_product_price' %>"><%= link_to("价格", products_path(:order => "by_product_price")) %></li>
    </ul>
  </div>

  <div class="productList-wrap w1200 pt20 bc">
    <%= render :partial => "products/product_list"%>
  </div>
</div>

<div class="category_sidebar tc border f12">
  <% Category.all.each do |category| %>
    <%= link_to category.name, products_path(category: category.name) %>
  <% end %>
  <a class="backtop" href="javascript:;"><i class="fa fa-arrow-circle-up"></i></a>
</div>

app/views/products/remove_buying_quantity.js.erb
$('.countNumber-btn-sub').bind('ajax:success', function(e, data) {
		$('.countNumber-input').val('<%= @product.buying_quantity %>')
});

app/views/products/search.html.erb
<div class="w1200 clearfix bc mt30 pb20 pr">
  <div class="logo fl"><%=link_to("小小食杂铺", products_path, class: "col-red")%></div>
  <div class="fl ml40 mt10">
    <%= render :partial => "products/search_bar" %>
  </div>
  <div class="pa mt10 cart-wrap">
    <%= render :partial => "products/cart" %>
  </div>
</div>
<%= render :partial => "products/menu" %>
<div class="minHeight1000 bg-gray">
  <div class="productList-wrap w1200 pt30 bc">
    <% if @products.present? %>
      <ul class="productList clearfix pb20">
        <% @products.each_with_index do |product, index| %>
          <%= render :partial => "product_item", locals: { product: product, index: index } %>
        <% end %>
      </ul>
    <% else %>
      <p class="tc mt100">亲，没有搜索到商品哦，要不换个关键词试试？</p>
    <% end %>
  </div>
  <h3 class="recommentTitle col-red ml40 w1200 bc">热门推荐</h3>
  <div class="productList-wrap w1200 pt20 bc">
    <ul class="productList clearfix pb20">
      <% Product.all.includes(:photos).sort_by {|product| product.favorites.count}.reverse.each_with_index do |product, index| %>
        <% if index < 5 %>
          <%= render :partial => "product_item", locals: { product: product, index: index } %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/products/show.html.erb
<div class="header_placeholder h80"></div>    
<div class="header">
  <div class="w1200 clearfix bc mt30 pb20 header_content pr">
    <div class="logo fl"><%=link_to("小小食杂铺", products_path, class: "col-red")%></div>
    <div class="fl ml40 mt10">
      <%= render :partial => "products/search_bar" %>
    </div>
    <div class="pa mt10 cart-wrap">
      <%= render :partial => "products/cart" %>
    </div>
  </div>
</div>

<%= render :partial => "products/menu" %>

<div class="detail mt20 w1200 bc pb50">
  <p class="location col-gray"><%= link_to("首页", products_path)%> >
    <% Category.all.each do |category| %>
          <% if @product.category.name == category.name %>
        <%= link_to category.name, products_path(category: category.name), class: "link" %>
    <% end %>
    <% end %>
    > <%= @product.title %></p>
  <div class="intro clearfix">
    <div class="cover fl">
      <div class="intro-bigPic border pr">
        <div class="magnifier-preview border" id="preview"></div>
        <% if @photos.present? %>
          <a class="magnifier-thumb-wrapper" href="javascript:;">
            <img
              id="thumb"
              src="<%= @photos.first.avatar.medium.url %>"
              data-large-img-wrapper="preview"
              data-large-img-url="<%= @photos.first.avatar.medium.url %>">
          </a>
        <% end %>
      </div>
      <ul class="intro-preview clearfix">
        <% if @photos.present? %>
          <% @photos.each_with_index do |p, index| %>
            <% if index == 0 %>
              <li class="border intro-preview-item intro-preview-activeItem fl">
            <% else %>
              <li class="border intro-preview-item fl">
            <% end %>
            <% if index < 5 %>
              <%= image_tag p.avatar.medium.url %>
            <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <p class="mt20 f12">
        <% if current_user && current_user.is_favorite_of?(@product) %>
          <i class="fa fa-star col-red"></i>
          <%= link_to('收藏'.html_safe, favorite_product_path(@product, type: "unfavorite"), method: :put, class: "col-red") %>
        <% else %>
          <i class="fa fa-star-o"></i>

          <%= link_to('收藏'.html_safe, favorite_product_path(@product, type: "favorite"), method: :put) %>
        <% end %>
        <span class="intro-favorite-count">（<%= @product.favorites.count %>人气）</span>
      </p>
    </div>

    <div class="intro-text fr">
      <h3 class="f20 ell fb"><%= @product.title %></h3>
      <p class="intro-text-desc"><%= @product.description %></p>
      <p class="intro-text-value bg-gray">
        <span class="pl20 pr30">售价</span><span class="price f24 fb col-red">￥<%= @product.price %></span>
      </p>
      <p class="intro-text-service">
        <span class="pl20 pr30">运费</span><span>满99元包邮 | 正品保证</span>
      </p>
      <p class="intro-text-count">
      <span class="pl20 pr30">库存</span><span id="quantity"><%= @product.quantity %></span>
      </p>
      <div class="intro-text-quantity clearfix">
        <span class="pl20 pr30 fl">数量</span> 
        <div class="countNumber fl mt10">
          <%= link_to("-", remove_buying_quantity_product_path(@product), class: "countNumber-btn countNumber-btn-sub", method: :post, remote: true) %>
          <input class="countNumber-input" type="text" value="<%= @product.buying_quantity %>">
          <%= link_to("+", add_buying_quantity_product_path(@product), class: "countNumber-btn countNumber-btn-plus", method: :post, remote: true) %>
        </div>
      </div>
      <p class="intro-text-btnWrap">
        <%= render :partial => "products/cart_btn"%>
      </p>
    </div>
  </div>

  <div class="productDetail border mt40">
    <ul class="productDetail-tabList bg-gray clearfix">
      <li class="productDetail-tabList-tab productDetail-tabList-activeTab fl pl50 pr50">
        商品详情
      </li>
      <li class="productDetail-tabList-tab fl pl50 pr50">
        商品评价(<%= @product.posts.count%>)
      </li>
    </ul>
    <div class="productDetail-contentWrap">
      <div class="productDetail-content pt20 tc pb20" style="display: block;">
        <div class="productDetail-introImg">
          <% if @prints.present? %>
            <% @prints.each_with_index do |p, index| %>
                <%= image_tag p.avatar.medium.url %>
            <% end %>
          <% else %>
              <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
          <% end %>
        </div>
        <p class="mt20 mb20"><%= @product.detail %></p>
      </div>
      <div class="productDetail-content pt30 tc pb20">
        <div class="productDetail-evaluation w200 bc">
          <div class="intro-text-count clearfix mt10">
            <div class="fl mr10">味道: </div>
            <div class="star-rating" data-score= <%= @avg_post %> ></div>
          </div>
          <div class="intro-text-count clearfix mt10">
            <div class="fl mr10">外观: </div>
            <div class="star-look" data-score= <%= @avg_look %> ></div>
          </div>
          <div class="intro-text-count clearfix mt10">
            <div class="fl mr10">价格: </div>
            <div class="star-price" data-score= <%= @avg_price %> ></div>
          </div>
        </div>
        <ul class="commentList mt70">
          <% @posts.each do |post| %>
            <li class="commentList-item w700 pt10 pb10 bc clearfix">
              <p class="fl content tl f12">
                <%= emojify post.content  %><br>
                <% if post.graphics.present? %>
                  <% post.graphics.each_with_index do |p, index| %>
                      <%= image_tag p.avatar.medium.url, class: "commentImage border" %>
                  <% end %>
                <% end %>
                <br>
                <img src="https://ww2.sinaimg.cn/large/006tKfTcgy1fczn4z618nj301a010mwz.jpg" class="commentBigImage">
              </p>
              <p class="fr name ell tr f12">
                <%= post.user.email %>
              </p>
            </li>
          <% end %>
        </ul>
        <p class="comment-say mt20 mb20">
          <%= link_to("我来说两句", new_product_post_path(@product),
              :class => "g-btn pl15 pr15 mt20 ml20 tc col-red f20 bg-red bc") %>
        </p>
      </div>
    </div>
  </div>
</div>