config/routes.rb
Rails.application.routes.draw do
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash

    end
  end
  resources :carts do
    collection do
      delete :clean
      get :checkout
    end
  end
  namespace :account do
    resources :orders
  end
  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end
  resources :cart_items do
    member do
      post :add_quantity
      post :remove_quantity
    end
  end
  resources :users, only: [:index]
  resources :messages, only: [:new, :create]
  resources :categories
  resources :products do
    put :favorite, on: :member
    resources :favorite do
      end
    member do
      post :add_to_cart
      post :upvote
      post :add_buying_quantity
      post :remove_buying_quantity
    end
    collection do
      get :search
    end
    resources :posts
  end
   devise_for :user, controllers: {
     passwords: 'users/passwords',
     registrations: 'users/registrations',
     sessions: 'users/sessions'
   }
  root 'welcome#index'

  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def clean!
    cart_items.destroy_all
  end

  def add_product_to_cart(product)
    ci = cart_items.build
    ci.product = product
    ci.quantity = product.buying_quantity
    ci.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/graphic.rb
class Graphic < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :post
end

app/models/order.rb
class Order < ApplicationRecord
  include Tokenable
  
  belongs_to :user
  has_many :product_lists
  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  def set_payment_with!(method)
    self.update_columns(payment_method: method)
  end

  def pay!
    self.update_columns(is_paid: true )
  end

include AASM
  aasm do
  state :order_placed, initial: true
  state :paid
  state :shipping
  state :shipped
  state :order_cancelled
  state :good_returned


  event :make_payment, after_commit: :pay! do
    transitions from: :order_placed, to: :paid
  end

  event :ship do
    transitions from: :paid,         to: :shipping
  end

  event :deliver do
    transitions from: :shipping,     to: :shipped
  end

  event :return_good do
    transitions from: :shipped,      to: :good_returned
  end

  event :cancell_order do
    transitions from: [:order_placed, :paid], to: :order_cancelled
  end
end
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
belongs_to :product
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :product
  has_many :graphics
  accepts_nested_attributes_for :graphics
  validates :content, presence: true 
end

app/models/print.rb
class Print < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :photos
  accepts_nested_attributes_for :photos
  belongs_to :category
  validates :category_id, presence: true
  belongs_to :user
  has_many :favorites
  has_many :fans, through: :favorites, source: :user
  has_many :votes, dependent: :destroy
  has_many :posts
  has_many :prints
  accepts_nested_attributes_for :prints
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
           acts_as_messageable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :orders

         def admin?
           is_admin
         end
         def mailboxer_email(object)
           email
         end
         has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "25x25#" }, :default_url => "/images/:style/missing.png"
         validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

         has_many :products
         has_many :favorites
         has_many :favorite_products, :through => :favorites, :source => :product
         def is_favorite_of?(product)
           favorite_products.include?(product)
         end
         has_many :posts
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :product
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def emojify(content, **options)
    Twemoji.parse(h(content), options).html_safe if content.present?
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end 

app/helpers/orders_helper.rb
module OrdersHelper
   def render_order_paid_state(order)
     if order.is_paid?
       "已付款"
     else
       "未付款"
     end
   end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<div class="w1200 bc mt20">
	<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
    <% end %>
    <% end %>	
</div>

app/views/common/_footer.html.erb
<!-- <div id="sidebar" class="sidebar f12 mt30">
  <ul>
    <li class="backtop"><i class="fa fa-arrow-circle-up"></i></li>
    <li class="support">
      <i class="fa fa-thumbs-o-up"></i>
      <div class="ewm">
        <p>
          觉得不错嘛？<br>
          来，动动小手<br>
          <a href="https://fullstack.xinshengdaxue.com/works/201" target="_blank" class="col-red">帮我们投个票</a><br>
          谢谢^_^
        </p>
      </div>
    </li>
  </ul>
</div> -->

<script>
  window.intercomSettings = {
    app_id: "iveo0tv7"
  };
</script>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/iveo0tv7';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>

<footer class="footer">
	<p>关于我们 <span>|</span> 帮助中心 <span>|</span> 开放平台 <span>|</span> 诚聘英才 <span>|</span> 联系我们 <span>|</span> 网站合作 <span>|</span> 友情链接</p>
	<p>
    <span class="logo-text">Copyright ©2017 购物商店</span>
    <span class="icp-center">Design by 郑智 & 陈俊鸿</span>
	</p>
</footer>

app/views/common/_navbar.html.erb
<div class="navbar-wrap clearfix pl10 pr10 bg-gray f12">
  <div class="jh_navbar w1200 bc">
    <div class="jh_navbar-left fl"><!-- <i class="fa fa-home f16 mr5"></i> --><%=link_to("欢迎来到小小食杂铺！", products_path)%></div>
    <ul class="jh_navbar-list fr">

    <% if !current_user %>
      <li class="fl jh_navbar-listItem pr10 pl10">
        <%= link_to("注册", new_user_registration_path) %>
      </li>
      <li class="jh_navbar-spacer fl"></li>
      <li class="fl jh_navbar-listItem pr10 pl10">
        <%= link_to("登入", new_user_session_path) %>
      </li>
    <% end %>

    <% if current_user %>
     <li class="fl jh_navbar-listItem pr10 pl10">
       Hi! <% if current_user.nickname.present? %>
            <%= current_user.nickname%>
           <% else %>
       <%= current_user.email %>
       <% end %>
      </li>
      <li class="jh_navbar-spacer fl"></li>
      <li class="fl jh_navbar-listItem pr10 pl10">
      <%= link_to(' 已收藏的商品'.html_safe, product_favorite_index_path(current_user.favorite_products)) %>
      </li>
      <li class="jh_navbar-spacer fl"></li>
      <li class="fl jh_navbar-listItem pr10 pl10">
        <%= link_to("我的订单", account_orders_path )%>
      </li>
      <li class="jh_navbar-spacer fl"></li>
      <li class="fl jh_navbar-listItem pr10 pl10">
        <!-- <%= link_to '站内信', conversations_path %> -->
      </li>
      <!-- <li class="jh_navbar-spacer fl"></li>
      <li class="fl jh_navbar-listItem pr10 pl10">
        <%= link_to '账号设置',edit_user_registration_path %>
      </li> -->
      <li class="jh_navbar-spacer fl"></li>
      <% if current_user.admin?%>
        <li class="fl jh_navbar-listItem pr10 pl10">
          <%= link_to '后台管理',admin_products_path %>
        </li>

        <li class="jh_navbar-spacer fl"></li>
      <% end %>
      <li class="fl jh_navbar-listItem pr10 pl10">
        <%= link_to("登出", destroy_user_session_path, method: :delete) %>
      </li>
    <% end %>

    </ul>
  </div>
</div>

<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog" role="document">
    <div class="loginmodal-container">
       <h2>Log in</h2>
       <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
         <div class="form-inputs">
           <%= f.input :nickname, label: "Name"%>
           <%= f.input :email, required: false, autofocus: true %>
           <%= f.input :password, required: false %>
           <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
         </div>
         <div class="form-actions">
           <%= f.button :submit, "Log in" %>
         </div>
       <% end %>
    </div>
  </div>
</div>


<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="loginmodal-container">
      <h2>注册</h2>
        <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
        <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :nickname, label: "Name"%>
          <%= f.input :email, required: true, autofocus: true %>
          <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
          <%= f.input :password_confirmation, required: true %>
        </div>
        <div class="form-actions">
            <%= f.button :submit, "Sign up" %>
        </div>
      <% end %>
    </div>
  </div>
</div>